name=RB_Nexus
version=0.2.2
author=Sakda-Oil
maintainer=Sakda-Oil
sentence=Hardware drivers, board identification and examples for RB_Nexus ESP32-WROOM-32.
paragraph=Included with RB_Nexus Boards Manager package. Provides drivers for PCA9685 motors/servos, MCP3208 12-bit SPI ADC, 4-channel encoders, and digital I/O.
category=Other
url=https://github.com/Sakda-Oil/RB_Nexus_LIBRARY
architectures=esp32
includes=RB_Nexus.h
depends=MPU9250 (=0.4.8), Adafruit BNO08x (=1.2.7)
