name=RB_Nexus
version=0.1.2
author=Sakda-Oil
maintainer=Sakda-Oil
sentence=Board identification and examples for RB_Nexus ESP32-WROOM-32.
paragraph=Included with RB_Nexus Boards Manager package. Peripheral connector mapping is pending a schematic.
category=Other
url=https://github.com/Sakda-Oil/RB_Nexus_LIBRARY
architectures=esp32
includes=RB_Nexus.h
